### ISSUE TITLE
KeyError: 'Tags'

### ISSUE THREAD

**Issue by deng1604** [yangyan22/Token-Mixer#1]
```
  File "D:\Project\newCode\Token-Mixer\modules\datasets.py", line 71, in __getitem__
    for j in example['Tags']:
KeyError: 'Tags'
```
当我运行这个项目时，出现了如上的报错。可以麻烦作者提供两个数据集对应的annotation.json文件吗？
或者，介绍下`Tags`这个东西是怎样生成的，谢谢！

**Comment by yangyan22** [comment]
在MIMIC-CXR数据集，直接采用了“mimic-cxr-2.0.0-chexpert”的14个多标签类别转化为对应的文本如“Support Device”，在IU X-ray数据集，将原始xml文件中的MeSH拿过来作为Tag。如果为了解决报错跑起来，可以不传入Tags到dataloader，将datasets.py文件中的66-73行进行修改，例如73行的sample = (image_id, image, report_ids, report_masks, seq_length, tok_ids, length)改为sample = (image_id, image, report_ids, report_masks, seq_length, report_ids, length)

**Comment by deng1604** [comment]
好的，谢谢作者！
> 在IU X-ray数据集，将原始xml文件中的MeSH拿过来作为Tag。


我看了下其中的xml文件，
```xml
   <MeSH>
   
      <major>Cardiomegaly/borderline</major>
   
      <major>Pulmonary Artery/enlarged</major>
   
      <automatic>sternotomy</automatic>

   </MeSH>
```
请问你是只用的其中的`major`还是两个都用到了呢？ 另外，作者您可以发我下IU Xray数据集对应的这个文件吗，我的邮箱是：1803870908@qq.com 🌹

**Comment by deng1604** [comment]
作者您好，不方便发文件的话，就算了。
可以告诉我，你是用的 xml 文件中的，major、automatic，还是两个都用到了呢？

**Comment by yangyan22** [comment]
已发邮件，请查收

**Comment by deng1604** [comment]
谢谢🌹🌹🌹

**Comment by deng1604** [comment]
另外，我在运行IU Xray数据集的代码时，在epoch=39时出现了错误，前面的epoch，是可以运行的。
```
Epoch 39 - Training:   0%|                                                                                                                                                                                                  | 0/64 [00:13<?, ?it/s] 
Traceback (most recent call last):
  File "D:\Project\newCode\Token-Mixer\train.py", line 125, in <module>
    main()
  File "D:\Project\newCode\Token-Mixer\train.py", line 118, in main
    trainer.train()
  File "D:\Project\newCode\Token-Mixer\modules\trainer_alter.py", line 79, in train
    result = self._train_epoch(epoch)
  File "D:\Project\newCode\Token-Mixer\modules\trainer_alter.py", line 228, in _train_epoch
    output = self.model(images, reports_ids, tok_ids,  mode='train', tags=self.args.tags, epoch_id=epoch)
  File "C:\Users\18038\.conda\envs\env2\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Project\newCode\Token-Mixer\modules\models_alter.py", line 122, in forward
    replace = random.sample(range(0, self.L), a)
  File "C:\Users\18038\.conda\envs\env2\lib\random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```
在`model_alter.py`中：
```python
class Model(nn.Module):
    def forward(self, images, targets=None, tok=None, mode='train', tags=0, epoch_id=0):
        ......

        if epoch_id % self.args.RoundGap == self.args.RoundGap - 1:  # 我这里，当epoch是39时，出现了错误。     39 % 4 == 3 满足条件，进入下面的代码
            a = int((epoch_id + 1) / self.args.RoundGap)  # 40 / 4 ，即 10
            feats = sturctured_emb_0

            # self.L = (8 - self.args.kernel) ** 2，而kernel默认是5，则L为：(8 - 5)^2 = 9
            # 当epoch为39时，下面的语句为：random.sample(range(0, 9), 10)
            replace = random.sample(range(0, self.L), a)
```
`random.sample(range(0, self.L), a)`，这个语句中，a 必须满足 `0 <= a <= self.L`

请问，我该怎么修改呢；或者是参数，该怎么调整呢？

**Comment by yangyan22** [comment]
对应参数a = int((epoch_id + 1) / self.args.RoundGap)，可以改为a=5（大于0小于9的常数）就可以了

**Comment by deng1604** [comment]
好的，谢谢！
